# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore super-service/src/SuperService.csproj
    - name: Build
      run: dotnet build super-service/src/SuperService.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test super-service/test/*.csproj --verbosity normal --logger "trx;LogFileName=TestResults.trx"
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: dotnet test
        reporter: dotnet-trx
        path: '**/TestResults.trx'
  
  checkov-scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        output_format: cli,sarif
        output_file_path: console,results.sarif
        skip_check: CKV_DOCKER_2 
        skip_framework: helm
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: results.sarif

  dockerbuild:
    needs: checkov-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t aspnetcore/superapp:${{ github.run_id }} .
    - uses: anchore/sbom-action@v0
      with:
        image: aspnetcore/superapp:${{ github.run_id }}
        format: cyclonedx