# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore super-service/src/SuperService.csproj
    - name: Build
      run: dotnet build super-service/src/SuperService.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test super-service/test/*.csproj --verbosity normal --logger "trx;LogFileName=TestResults.trx"
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: dotnet test
        reporter: dotnet-trx
        path: '**/TestResults.trx'

  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t aspnetcore/superapp .